### ISSUE TITLE
What is the retriever name for colbertretriever?

### ISSUE THREAD

**Issue by RohithDAces** [datastax/ragstack-ai#520]
I had used this code, answers = retriever.retrieve("What's arctic botany", k=2). 
But I get this error.
Error: 'ColbertRetriever' object has no attribute 'retrieve'.

Initially I installed pip install ragstack-ai-colbert in my local. 
These all are coming based on this module.

**Comment by nicoloboschi** [comment]
Hey @RohithDAces I'm assuming you're using the vanilla ColbertRetriever (`ragstack_colbert.colbert_retriever. ColbertRetriever`. The method for retrieving based on a text is `text_search`.

See the notebooks here: https://github.com/datastax/ragstack-ai/blob/main/examples/notebooks/RAGStackColBERT.ipynb 

I see the [docs is outdated](https://docs.datastax.com/en/ragstack/examples/colbert.html), we will fix it soon
